spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:mysql://localhost:3306/test
    name: test
  main:
    allow-circular-references: true
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    org.springframework.r2dbc: debug